language: python
# Don't use the Travis Container-Based Infrastructure
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: linux
      python: "3.6-dev"
    - os: linux
      python: "3.7-dev"
    - os: linux
      python: "nightly"

    - os: osx
      sudo: required
      language: generic

  allow_failures:
      - python: "3.6-dev"
      - python: "3.7-dev"
      - python: "nightly"
      - os: "osx"
addons:
  apt:
    packages:
        - git
        - pandoc
before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew update;
      brew install python3 pandoc;
      python3 -m venv venv;
      source venv/bin/activate;
      pip install . test
  fi
# command to install dependencies
install:
    - "pip install --upgrade pip pipenv" # upgrade to latest pip (needed on py3.4)
    - "pipenv install -e .[test]"
# command to run tests
script: "pipenv run py.test --cov=git_repo --cov-report term-missing tests"
